### ISSUE TITLE
No decode function for Docopt

### ISSUE THREAD

**Issue by dineshadepu** [BurntSushi/rust-error-handling-case-study#2]
In the case study, while parsing the arguments to `Docopt` struct, it says,

```
Compiling city-pop v0.1.0 (file:///home/dinesh/prog/rust/city-pop)
error[E0599]: no method named `decode` found for type `docopt::Docopt` in the current scope
  --> src/main.rs:28:32
   |
28 |         Ok(dopt) => match dopt.decode() {
   |                                ^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `city-pop`.
```

I saw the previous versions of the `docopt` crate, I found it in `0.6.*` version. But Cargo is 
automatically using version `0.9.0` which doesn't have this function.

**Comment by BurntSushi** [comment]
Cargo will most certainly not automatically use `0.9.0` here. The Cargo.toml specifically says `docopt 0.6.0`.

The current `Cargo.lock` file does not appear to build with the most recent version of Rust though. I've updated that and the project builds again.

Ideally, we would update the example to use the latest version of each library (like serde, docopt and csv 1.0), but that's a bit more work and requires editing parts of the article itself.
